# Generated by Django 5.0.2 on 2024-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chathistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='history_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
