# Generated by Django 5.0.2 on 2024-05-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(max_length=50)),
                ('message_body', models.TextField()),
                ('message_reference_code', models.CharField(max_length=100)),
                ('message_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('is_urgent', models.BooleanField(blank=True, null=True)),
                ('is_responded', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_reference_code', models.CharField(max_length=100)),
                ('message_response', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_response', to='main.inquirymessage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_responded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
