# Generated by Django 5.0.2 on 2024-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryresponse',
            name='read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
